version: '3'
services:

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=growi-slackbot-proxy
      - MYSQL_PASSWORD=YrkUi7rCW46Z2N6EXSFUBwaQTUR8biCU
      - MYSQL_DATABASE=growi-slackbot-proxy
    volumes:
      - /data/db

networks:
  default:
    external:
      name: growi_devcontainer_default
